### ISSUE TITLE
Jedi error

### ISSUE THREAD

**Issue by luipir** [YoannQDQ/qgis-better-editor#2]
Hi, I suppose it¡s a nice plugin... btw I've error runing formatting or check
![Screenshot from 2020-06-22 09-22-53](https://user-images.githubusercontent.com/3344634/85259901-1d571200-b46a-11ea-814c-a0bbaf0b2a96.png)

I hadn't time to investigate more... let me knwo if you need more info

cheers

**Comment by YoannQDQ** [comment]
The plugin relies on Jedi 0.17.1, but you have 0.13.3 installed.
I could force an upgrade, but I'm afraid it could break existing code on your part.

The best I can think of right now is to ask for confirmation before upgrading Jedi (QGIS restart will be required).

**Comment by YoannQDQ** [comment]
(will be fixed in v 1.2.0)
